# Generated by Django 2.2.3 on 2019-07-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_barras', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('precio_venta_uno', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('precio_venta_dos', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('observaciones', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
