# Generated by Django 2.2.3 on 2019-07-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encabezado',
            name='id',
        ),
        migrations.AlterField(
            model_name='encabezado',
            name='no_venta',
            field=models.IntegerField(default=1001, primary_key=True, serialize=False, unique=True),
        ),
    ]
