# Generated by Django 2.2.3 on 2019-07-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20190704_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encabezado',
            name='no_venta',
            field=models.AutoField(default=1001, primary_key=True, serialize=False, unique=True),
        ),
    ]
