# Generated by Django 2.2.3 on 2019-07-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20190704_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encabezado',
            name='no_venta',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
