# Generated by Django 2.2.3 on 2019-07-04 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20190704_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='encabezado_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ventas.Encabezado'),
            preserve_default=False,
        ),
    ]
